# nhập dữ liệu

In [1]:
import pandas as pd
import sqlite3

# Tạo dữ liệu student
student = pd.DataFrame({
    "student_id":[1,2,3,4,5,6,7,8,9,10],
    "name":["Nguyen Minh Hoang","Tran Thi Lan","Pham Van Nam","Le Thanh Huyen",
            "Vu Quoc Anh","Dang Thuy Linh","Bui Tien Dung","Ho Ngoc Mai",
            "Duong Huu Phuc","Cao Thi Hanh"],
    "class":["May Tinh","Kinh Te","Toan Tin","Toan Tin","May Tinh",
             "May Tinh","Kinh Te","Toan Tin","Kinh Te","May Tinh"],
    "course_id":[12,34,None,20,24,24,34,20,None,None],
    "score":[6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})

# Tạo dữ liệu course
course = pd.DataFrame({
    "id":[12,34,26],
    "course_name":["Giai tich","Thong ke","Tin hoc"]
})

# Kết nối SQLite
conn = sqlite3.connect(':memory:')
student.to_sql('student', conn, index=False, if_exists='replace')
course.to_sql('course', conn, index=False, if_exists='replace')

3

## Câu 1:

### Sử dụng tích Decartes.

In [4]:
display(pd.read_sql_query("""select *
from student, course""", conn))

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

### Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.

In [6]:
# INNER JOIN
pd.read_sql("""
SELECT * FROM student s
INNER JOIN course c ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

In [7]:
# LEFT JOIN
pd.read_sql("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

In [8]:
# RIGHT JOIN
pd.read_sql("""
SELECT * FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin hoc         NaN               None      None        NaN    NaN

In [9]:
# FULL OUTER JOIN
pd.read_sql("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id
UNION
SELECT * FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

## Câu 2:

### cập nhật những giá trị course_id còn thiếu trong bảng student

In [13]:
print("Dữ liệu student ban đầu")
display(pd.read_sql_query("SELECT * FROM student", conn))

# Điền course_id còn thiếu bằng các giá trị nằm trong bảng course.
# Ở đây chọn id nhỏ nhất trong course = 12 để điền cho NULL.
conn.execute("""
UPDATE student
SET course_id = (SELECT MIN(id) FROM course)
WHERE course_id IS NULL
""")

# Xóa các bản ghi có course_id không tồn tại trong course
conn.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

print("Dữ liệu student sau khi làm sạch")
display(pd.read_sql_query("SELECT * FROM student", conn))

Dữ liệu student ban đầu

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           7      Bui Tien Dung   Kinh Te       34.0    9.2
4           9     Duong Huu Phuc   Kinh Te        NaN    7.2
5          10       Cao Thi Hanh  May Tinh        NaN    7.0

Dữ liệu student sau khi làm sạch

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       12.0    7.9
3           7      Bui Tien Dung   Kinh Te       34.0    9.2
4           9     Duong Huu Phuc   Kinh Te       12.0    7.2
5          10       Cao Thi Hanh  May Tinh       12.0    7.0

### a. Tổng số sinh viên, điểm trung bình của từng lớp.

In [15]:
pd.read_sql_query("""
select class, count(student_id) as so_sinh_vien, avg(score) as diem_trung_binh
from student
group by class
""", conn)

      class  so_sinh_vien  diem_trung_binh
0   Kinh Te             3         8.533333
1  May Tinh             2         6.850000
2  Toan Tin             1         7.900000

### b. Tổng số sinh viên, điểm trung bình của từng môn học.

In [16]:
# Tổng số sinh viên, điểm trung bình của từng môn học.
pd.read_sql_query("""
select c.course_name, count(s.student_id) as so_sinh_vien, avg(s.score) as diem_trung_binh
from student s
JOIN course c ON s.course_id = c.id
group by c.course_name
""", conn)

  course_name  so_sinh_vien  diem_trung_binh
0   Giai tich             4              7.2
1    Thong ke             2              9.2

### c. Phân loại thi đua theo số điểm của từng môn học biết:
i. Điểm TB ≥ 9.0: Xuất sắc.

ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.

iii. Điểm TB < 6.0: Kém.

In [17]:
pd.read_sql_query("""SELECT c.course_name, AVG(s.score) AS average_score,
CASE WHEN AVG(s.score) >= 9.0 THEN 'Xuất sắc'
WHEN AVG(s.score)
BETWEEN 6.0 AND 8.9 THEN 'Tốt' ELSE 'Kém'
END AS classification
FROM student s JOIN course c ON s.course_id = c.id GROUP BY c.course_name""", conn)

  course_name  average_score classification
0   Giai tich            7.2            Tốt
1    Thong ke            9.2       Xuất sắc

## Câu 3:Hãy xếp hạng sinh viên thông qua:

### a. Điểm số.

In [19]:
pd.read_sql_query("""SELECT *,
RANK() OVER (ORDER BY score DESC) as rank_score
FROM student""", conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te       34.0    9.2           1
1           7      Bui Tien Dung   Kinh Te       34.0    9.2           1
2           3       Pham Van Nam  Toan Tin       12.0    7.9           3
3           9     Duong Huu Phuc   Kinh Te       12.0    7.2           4
4          10       Cao Thi Hanh  May Tinh       12.0    7.0           5
5           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           6

### b. Điểm số theo lớp học.

In [21]:
pd.read_sql_query("""SELECT *,
RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_score
FROM student""", conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te       34.0    9.2           1
1           7      Bui Tien Dung   Kinh Te       34.0    9.2           1
2           9     Duong Huu Phuc   Kinh Te       12.0    7.2           3
3          10       Cao Thi Hanh  May Tinh       12.0    7.0           1
4           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           2
5           3       Pham Van Nam  Toan Tin       12.0    7.9           1

### c. Điểm số theo mã môn học

In [22]:
pd.read_sql_query("""SELECT *,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_score
FROM student""", conn)

   student_id               name     class  course_id  score  rank_score
0           3       Pham Van Nam  Toan Tin       12.0    7.9           1
1           9     Duong Huu Phuc   Kinh Te       12.0    7.2           2
2          10       Cao Thi Hanh  May Tinh       12.0    7.0           3
3           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           4
4           2       Tran Thi Lan   Kinh Te       34.0    9.2           1
5           7      Bui Tien Dung   Kinh Te       34.0    9.2           1

## Top 3 và Bottom 3 sinh viên theo từng trường hợp xếp hạng

### a. Điểm số

In [23]:
# Top 3 sinh viên đạt thứ hạng cao nhất theo điểm số
display(pd.read_sql_query("""SELECT * FROM (SELECT *, RANK() OVER (ORDER BY score DESC) as rank_score FROM student) WHERE rank_score <= 3""", conn))

# Top 3 sinh viên đạt thứ hạng thấp nhất theo điểm số
display(pd.read_sql_query("""SELECT * FROM (SELECT *, RANK() OVER (ORDER BY score ASC) as rank_score FROM student) WHERE rank_score <= 3""", conn))

   student_id           name     class  course_id  score  rank_score
0           2   Tran Thi Lan   Kinh Te       34.0    9.2           1
1           7  Bui Tien Dung   Kinh Te       34.0    9.2           1
2           3   Pham Van Nam  Toan Tin       12.0    7.9           3

   student_id               name     class  course_id  score  rank_score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           1
1          10       Cao Thi Hanh  May Tinh       12.0    7.0           2
2           9     Duong Huu Phuc   Kinh Te       12.0    7.2           3

### b. Điểm số theo lớp học.

In [24]:
# Top 3 sinh viên đạt thứ hạng cao nhất theo lớp học
display(pd.read_sql_query("""SELECT * FROM (SELECT *, RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_score FROM student) WHERE rank_score <= 3""", conn))

# Top 3 sinh viên đạt thứ hạng thấp nhất theo lớp học
display(pd.read_sql_query("""SELECT * FROM (SELECT *, RANK() OVER (PARTITION BY class ORDER BY score ASC) as rank_score FROM student) WHERE rank_score <= 3""", conn))

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te       34.0    9.2           1
1           7      Bui Tien Dung   Kinh Te       34.0    9.2           1
2           9     Duong Huu Phuc   Kinh Te       12.0    7.2           3
3          10       Cao Thi Hanh  May Tinh       12.0    7.0           1
4           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           2
5           3       Pham Van Nam  Toan Tin       12.0    7.9           1

   student_id               name     class  course_id  score  rank_score
0           9     Duong Huu Phuc   Kinh Te       12.0    7.2           1
1           2       Tran Thi Lan   Kinh Te       34.0    9.2           2
2           7      Bui Tien Dung   Kinh Te       34.0    9.2           2
3           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           1
4          10       Cao Thi Hanh  May Tinh       12.0    7.0           2
5           3       Pham Van Nam  Toan Tin       12.0    7.9           1

### c. Điểm số theo mã môn học

In [25]:
# Top 3 sinh viên đạt thứ hạng cao nhất theo mã môn học
display(pd.read_sql_query("""SELECT * FROM (SELECT *, RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_score FROM student) WHERE rank_score <= 3""", conn))

# Top 3 sinh viên đạt thứ hạng thấp nhất theo mã môn học
display(pd.read_sql_query("""SELECT * FROM (SELECT *, RANK() OVER (PARTITION BY course_id ORDER BY score ASC) as rank_score FROM student) WHERE rank_score <= 3""", conn))

   student_id            name     class  course_id  score  rank_score
0           3    Pham Van Nam  Toan Tin       12.0    7.9           1
1           9  Duong Huu Phuc   Kinh Te       12.0    7.2           2
2          10    Cao Thi Hanh  May Tinh       12.0    7.0           3
3           2    Tran Thi Lan   Kinh Te       34.0    9.2           1
4           7   Bui Tien Dung   Kinh Te       34.0    9.2           1

   student_id               name     class  course_id  score  rank_score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           1
1          10       Cao Thi Hanh  May Tinh       12.0    7.0           2
2           9     Duong Huu Phuc   Kinh Te       12.0    7.2           3
3           2       Tran Thi Lan   Kinh Te       34.0    9.2           1
4           7      Bui Tien Dung   Kinh Te       34.0    9.2           1

## Câu 4: Bổ sung trường `graduation_date` và tính toán thời gian tốt nghiệp.

In [30]:
# 1. Thêm cột (tránh lỗi khi chạy lại)
try:
    conn.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME;")
    conn.commit()
except:
    print("Cột đã tồn tại, bỏ qua")

# 2. Update đúng logic (dùng ROUND)
conn.execute("""
UPDATE student
SET graduation_date = datetime('now', '+' || ROUND(score) || ' days')
""")
conn.commit()

# 3. Hiển thị
display(pd.read_sql_query("SELECT * FROM student", conn))

Cột đã tồn tại, bỏ qua

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,2026-04-09 16:28:52
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,2026-04-11 16:28:52
2,3,Pham Van Nam,Toan Tin,12.0,7.9,2026-04-10 16:28:52
3,7,Bui Tien Dung,Kinh Te,34.0,9.2,2026-04-11 16:28:52
4,9,Duong Huu Phuc,Kinh Te,12.0,7.2,2026-04-09 16:28:52
5,10,Cao Thi Hanh,May Tinh,12.0,7.0,2026-04-09 16:28:52